version: "3.7"
services:
  nginx:
    image: nginx:latest
    container_name: nginx
    restart: unless-stopped
    tty: true
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./docker/nginx/site.conf:/etc/nginx/conf.d/site.conf
    networks:
      - router
    depends_on:
      - php
  php:
    image: php:7.4-fpm
    container_name: php
    restart: unless-stopped
    tty: true
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www/html
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    networks:
      - router
  composer:
    image: composer:latest
    command: ["composer", "install"]
    volumes:
      - .:/app
    networks:
      - router

# Docker Application Network
networks:
  router:
    driver: bridge